=== FakeDevy/uam_java_json_xml_patryk_malczewsi/zad_1_xml/uniwersytet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="uniwersytet">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="wydział" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="wydział">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="adres" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="pracownicy">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="pracownik" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="przedmioty">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="przedmiot" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nazwa" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="pracownik">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="imię" type="xs:string" />
        <xs:element name="nazwisko" type="xs:string" />
        <xs:element name="tytuł" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="kategoria">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="naukowy"/>
              <xs:enumeration value="administracyjny"/>
              <xs:enumeration value="techniczny"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="adres" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="adres">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ulica" type="xs:string" />
        <xs:element name="numer" type="xs:string" />
        <xs:element name="kod_pocztowy" type="xs:string" />
        <xs:element name="miejscowość" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="przedmiot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nazwa" type="xs:string" />
        <xs:element name="opis" type="xs:string" />
        <xs:element name="liczba_studentów">
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:minInclusive value="6"/>
              <xs:maxInclusive value="400"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="prowadzący" type="xs:IDREF" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="kod" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FakeDevy/uam_java_json_xml_patryk_malczewsi/zad_1_xml/uniwersytet.xml
<?xml version="1.0" encoding="UTF-8"?>
<uniwersytet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="uniwersytet.xsd">
  <wydział id="WMI" nazwa="Wydział Matematyki i Informatyki">
    <adres>Uniwersytetu Poznańskiego 4, Poznań</adres>
    <adres>Wieniawskiego 1, Poznań</adres>
    <pracownicy>
      <pracownik id="PRAC_1">
        <imię>Marek</imię>
        <nazwisko>Gałązka</nazwisko>
        <tytuł>Dr</tytuł>
        <kategoria>naukowy</kategoria>
        <adres>
          <ulica>Uniwersytetu Poznańskiego</ulica>
          <numer>5</numer>
          <kod_pocztowy>60-001</kod_pocztowy>
          <miejscowość>Poznań</miejscowość>
        </adres>
      </pracownik>
      <pracownik id="PRAC_2">
        <imię>Jan</imię>
        <nazwisko>Admin</nazwisko>
        <kategoria>techniczny</kategoria>
        <adres>
          <ulica>Uniwersytetu Przyrodniczego</ulica>
          <numer>1</numer>
          <kod_pocztowy>60-001</kod_pocztowy>
          <miejscowość>Luboń</miejscowość>
        </adres>
        <adres>
          <ulica>Galileusza</ulica>
          <numer>50</numer>
          <kod_pocztowy>60-001</kod_pocztowy>
          <miejscowość>Poznań</miejscowość>
        </adres>
      </pracownik>
    </pracownicy>
    <przedmioty>
      <przedmiot kod="CG">
        <nazwa>Grafika komputerowa</nazwa>
        <opis>Podstawy OpenGL</opis>
        <liczba_studentów>10</liczba_studentów>
        <prowadzący>PRAC_1</prowadzący>
      </przedmiot>
      <przedmiot kod="SOP">
        <nazwa>Systemy operacyjne</nazwa>
        <opis>Podstawy systemów z rodziny UNIX</opis>
        <liczba_studentów>50</liczba_studentów>
        <prowadzący>PRAC_1</prowadzący>
        <prowadzący>PRAC_2</prowadzący>
      </przedmiot>
    </przedmioty>
  </wydział>
</uniwersytet>
